export { default as AddPatietModal } from "./AddPatientModal";
export { default as TableTemplate } from "./TableTemplate";
export { default as AddMedicalInfoModal } from "./AddMedicalInfoModal";
export { default as AddUserModal } from "./AddUserModal";
export { default as ViewMedicalDetailsModal } from "./ViewMedicalRecordDetailsModal";
export { default as PatientSidebar } from "./PatientSidebar";
export { default as ManagePatientModal } from "./ManagePatientModal";
export { default as ReviewPermissionModal } from "./ReviewPermissions";
export { default as CustomIconButton } from "./CustomIconButton";
