import React from "react";
import {
  Backdrop,
  Box,
  CssBaseline,
  Stack,
  ThemeProvider,
} from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { useAppDispatch, useAppSelector } from "../app/hooks";
import { BannerContent, Banner, Loader } from "../components";
import ThemeConfiguration from "../configuration/ThemeConfiguration";
import { clearResponse } from "../features/ResponseReducer";
import { ToastContainer, toast } from "react-toastify";
import { isExpired } from "react-jwt";
import "../styles/Home.module.css";

export default function Home() {
  const { error, message, loading } = useAppSelector(
    (state) => state.ResponseReducer
  );
  const dispatch = useAppDispatch();

  const handleCloseNotifier = () => {
    dispatch(clearResponse());
  };

  function HandleNotifier() {
    Boolean(message) &&
      toast.success(message, {
        position: toast.POSITION.TOP_RIGHT,
        theme: "dark",
        onClose: handleCloseNotifier,
        toastId: "success",
      });

    Boolean(error) &&
      toast.error(error, {
        position: toast.POSITION.TOP_RIGHT,
        theme: "dark",
        onClose: handleCloseNotifier,
        toastId: "error",
      });

    return <Box></Box>;
  }
  return (
    <ThemeProvider theme={ThemeConfiguration}>
      <Stack>
        <CssBaseline />
        <Backdrop open={true} />

        {Boolean(error || message) && HandleNotifier()}
        <ToastContainer draggable={true} autoClose={3000} />
        <Head>
          <title>Ebi Health App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Banner />
        <BannerContent />
      </Stack>
    </ThemeProvider>
  );
}
