import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import BannerContent from "../components/BannerContent";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ebi Health App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <BannerContent />
    </div>
  );
}
